"""What happens when the AI model's answer cannot be used (FLAWS.md F34).

Found live on BGV: a Large request came back "Generated by: heuristic" and
created 49 generic tickets, with a reply saying the model was unreachable —
while the review agent's model calls were succeeding at the same moment. The
model had answered; its answer was the problem. Four gaps made that possible:

* no ``max_tokens`` was sent, so a long breakdown could be cut off mid-JSON;
* a cut-off answer raised a bare ``JSONDecodeError``, not ``DecompositionError``;
* with the model required, that error escaped the tools layer and crashed;
* a breakdown failure was reported as VALIDATION_ERROR — "not a work
  requirement" — instead of a failure.
"""

from __future__ import annotations

import sys
import types
from typing import Any

import pytest

from src.agent.delegated import to_contract
from src.classification import decompose
from src.classification.decompose import DecompositionError
from src.classification.validate import ProjectContext
from src.models.schemas import ResultStatus
from src.shared.contract import Outcome

# Captured at collection, before conftest's autouse stub replaces ``_chat``.
_REAL_CHAT = decompose._chat


def test_a_cut_off_answer_is_a_named_decomposition_error() -> None:
    truncated = '{"classification": "Large", "stories": [{"title": "Record consent", "desc'
    with pytest.raises(DecompositionError, match="cut off"):
        decompose._parse_json_object(truncated)


def test_a_cut_off_answer_whose_braces_happen_to_close_is_still_named() -> None:
    """The first brace to the last brace can span an incomplete structure."""
    truncated = '{"stories": [{"title": "a"}, {"title": "b", "subtasks": [{"x": 1}'
    with pytest.raises(DecompositionError):
        decompose._parse_json_object(truncated)


async def test_the_model_is_asked_for_enough_output(monkeypatch) -> None:
    seen: dict[str, Any] = {}

    class _Client:
        async def __aenter__(self):
            return self

        async def __aexit__(self, *exc):
            return None

        async def chat(self, **kwargs):
            seen.update(kwargs)
            return {"content": "{}"}

    module = types.ModuleType("agent_lib.gateway.ai")
    module.AiGatewayClient = _Client  # type: ignore[attr-defined]
    monkeypatch.setitem(sys.modules, "agent_lib.gateway.ai", module)
    monkeypatch.delenv("LTW_LLM_MAX_TOKENS", raising=False)

    await _REAL_CHAT("prompt")
    assert seen["max_tokens"] == decompose.DEFAULT_MAX_TOKENS


@pytest.mark.parametrize(
    "raw, expected", [("8000", 8000), ("", 16000), ("nope", 16000), ("0", 16000)]
)
def test_the_output_limit_is_configurable_and_safe(raw: str, expected: int, monkeypatch) -> None:
    monkeypatch.setenv("LTW_LLM_MAX_TOKENS", raw)
    assert decompose._max_tokens() == expected


async def test_a_required_model_failure_is_catchable_by_the_tools_layer(monkeypatch) -> None:
    """A gateway timeout used to escape ``except (DecompositionError, ...)``."""

    async def _chat(prompt: str) -> str:
        raise TimeoutError("gateway timed out")

    monkeypatch.setattr(decompose, "_chat", _chat)
    monkeypatch.setenv("LTW_REQUIRE_LLM", "true")

    with pytest.raises(DecompositionError, match="TimeoutError: gateway timed out"):
        await decompose.build_breakdown("Let recruiters record consent.", ProjectContext())
    with pytest.raises(DecompositionError, match="TimeoutError"):
        await decompose.triage("Let recruiters record consent.", ProjectContext())


async def test_the_fallback_never_runs_even_with_llm_not_required(monkeypatch) -> None:
    """Blocked whatever LTW_REQUIRE_LLM says: its tickets were boilerplate
    unrelated to the requirement (owner decision, 2026-09-25)."""

    async def _chat(prompt: str) -> str:
        raise TimeoutError("gateway timed out")

    monkeypatch.setattr(decompose, "_chat", _chat)
    monkeypatch.setenv("LTW_REQUIRE_LLM", "false")

    with pytest.raises(decompose.DecompositionError, match="gateway timed out"):
        await decompose.build_breakdown(
            "Let recruiters record a candidate's consent.", ProjectContext()
        )


def test_a_failed_breakdown_reaches_the_router_as_a_failure_not_an_invalid_request() -> None:
    """The user-facing half: VALIDATION_ERROR rendered as "Invalid request —
    this is not a work requirement" and the router never emails for that."""
    result = to_contract(
        {
            "status": ResultStatus.JIRA_CREATION_FAILED.value,
            "message": "A work breakdown could not be produced.",
            "validation_errors": ["Work breakdown could not be produced: cut off"],
        },
        run_id="r1",
        agent_version="4.3.9",
    )
    assert result.outcome is Outcome.FAILED
    assert "cut off" in " ".join(result.errors)


# --- F36: the breakdown request was shown the triage answer format ----------


def test_the_breakdown_prompt_carries_no_triage_examples() -> None:
    """Shown triage verdicts, the model answered a build with a verdict."""
    from src.prompts.templates import breakdown_prompt

    prompt = breakdown_prompt("Record address history.", "Project: BGV")
    assert '"verdict"' not in prompt.split("Return the breakdown JSON")[0]
    assert "never a" in prompt  # the explicit shape-only instruction


def test_the_breakdown_context_does_not_ask_the_model_to_judge_duplicates() -> None:
    context = ProjectContext(
        name="BGV",
        description="Background checks.",
        existing_titles=("BGV-65 — Implement Address Verification",),
    )
    breakdown_text = context.as_prompt_text(for_breakdown=True)
    triage_text = context.as_prompt_text()
    assert "BGV-65" in breakdown_text
    assert "say so" not in breakdown_text
    # Triage no longer sees them at all: on fresh BGV-15 it asked "does this
    # differ from BGV-2?" instead of the duplicate check answering (2026-09-25).
    assert "BGV-65" not in triage_text


async def test_a_triage_shaped_answer_is_a_short_readable_error(monkeypatch) -> None:
    """The exact live answer: a verdict object where a breakdown belonged."""

    async def _chat(prompt: str) -> str:
        return (
            '{"verdict": "CLARIFICATION_REQUIRED", "reason": "thin", '
            '"questions": ["Which candidates?"]}'
        )

    monkeypatch.setattr(decompose, "_chat", _chat)
    with pytest.raises(DecompositionError) as caught:
        await decompose.llm_breakdown("Record address history.", ProjectContext())
    message = str(caught.value)
    assert "did not match the breakdown format" in message
    assert "missing: classification" in message
    assert "unexpected: verdict" in message
    assert "errors.pydantic.dev" not in message
    assert len(message) < 300
