"""Structured review -> ADF and markdown preview."""

from __future__ import annotations

from jira.http import adf_to_text
from review.adf import render_review_to_adf, render_review_to_markdown
from review.models import (
    Confidence,
    Finding,
    FindingType,
    Priority,
    Readiness,
    ReadinessLevel,
    Review,
)


def _review():
    return Review(
        findings=[
            Finding(
                finding_type=FindingType.ASSUMPTION,
                description="Assumes the API supports OAuth",
                evidence_source="Target ABC-1 (description)",
                confidence=Confidence.HIGH,
            ),
            Finding(
                finding_type=FindingType.OPEN_QUESTION,
                description="What happens if the service is unavailable?",
                evidence_source="Meeting Transcript",
                confidence=Confidence.MEDIUM,
            ),
        ]
    )


def test_doc_shape():
    d = render_review_to_adf(_review(), "ABC-1")
    assert d["type"] == "doc"
    assert d["version"] == 1
    assert d["content"][0]["type"] == "heading"
    assert d["content"][0]["attrs"]["level"] == 2


def test_only_nonempty_sections_rendered():
    d = render_review_to_adf(_review(), "ABC-1")
    h3 = [n for n in d["content"] if n["type"] == "heading" and n["attrs"]["level"] == 3]
    titles = [h["content"][0]["text"] for h in h3]
    assert "Assumption" in titles
    assert "Open Question" in titles
    assert "Requirement Gap" not in titles  # empty category omitted


def test_empty_review_message():
    d = render_review_to_adf(Review(findings=[]), "ABC-1")
    assert "No assumptions" in adf_to_text(d)


def test_roundtrip_shows_descriptions_only_no_evidence_or_confidence():
    text = adf_to_text(render_review_to_adf(_review(), "ABC-1"))
    assert "Assumes the API supports OAuth" in text
    assert "What happens if the service is unavailable?" in text
    # evidence/confidence are kept in the data but NOT rendered in the comment
    assert "Evidence:" not in text
    assert "Confidence:" not in text
    assert "Target ABC-1 (description)" not in text


def test_footer_adds_rule_and_text():
    d = render_review_to_adf(_review(), "ABC-1", footer="Generated by Agent · 2026")
    assert any(n["type"] == "rule" for n in d["content"])
    assert "Generated by Agent" in adf_to_text(d)


def test_markdown_preview_format():
    md = render_review_to_markdown(_review(), "ABC-1")
    assert "## Requirement Review — ABC-1" in md
    assert "### Assumption" in md
    assert "- Assumes the API supports OAuth" in md
    # evidence/confidence sub-bullets are no longer rendered
    assert "Evidence:" not in md
    assert "Confidence:" not in md
    # empty categories are not rendered
    assert "### Requirement Gap" not in md


def _readiness():
    return Readiness(
        level=ReadinessLevel.NEEDS_MAJOR_CLARIFICATION,
        score=2,
        executive_summary="Big gap in auth.",
    )


def test_markdown_omits_readiness_block_when_none():
    md = render_review_to_markdown(_review(), "ABC-1")
    assert "Overall Readiness" not in md


def test_markdown_includes_readiness_block_when_provided():
    md = render_review_to_markdown(_review(), "ABC-1", readiness=_readiness())
    assert "**Overall Readiness:** Needs Major Clarification (score 2/5)" in md
    assert "_Big gap in auth._" in md


def test_adf_includes_readiness_block_when_provided():
    d = render_review_to_adf(_review(), "ABC-1", readiness=_readiness())
    text = adf_to_text(d)
    assert "Overall Readiness:" in text
    assert "Needs Major Clarification (score 2/5)" in text
    assert "Big gap in auth." in text


def test_priority_prefixes_bullet_when_set():
    review = Review(
        findings=[
            Finding(
                finding_type=FindingType.DEPENDENCY_QUESTION,
                description="Does ABC-9 land first?",
                priority=Priority.HIGH,
            )
        ]
    )
    md = render_review_to_markdown(review, "ABC-1")
    assert "- [HIGH] Does ABC-9 land first?" in md
    text = adf_to_text(render_review_to_adf(review, "ABC-1"))
    assert "[HIGH] Does ABC-9 land first?" in text


def test_no_priority_no_prefix():
    review = Review(
        findings=[Finding(finding_type=FindingType.ASSUMPTION, description="Assumes X")]
    )
    md = render_review_to_markdown(review, "ABC-1")
    assert "- Assumes X" in md
    assert "[HIGH]" not in md and "[MEDIUM]" not in md and "[LOW]" not in md
