"""@tool: post the approved review as a Jira comment (the only Jira write).

Accepts the human-approved markdown (preferred) or structured findings, converts
to ADF, appends a generated-by/timestamp footer, and POSTs. Best-effort: returns
``posted: False`` + error on failure rather than raising.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from typing import Any

from aetherion_sdk import tool
from dotenv import load_dotenv

from jira.client import jira_client_from_env
from review.adf import markdown_to_adf, render_review_to_adf
from review.models import Readiness
from review.parser import parse_findings

load_dotenv()
logger = logging.getLogger(__name__)


def _footer(workflow_id: str | None) -> str:
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    suffix = f" · wf {workflow_id}" if workflow_id else ""
    return f"Generated by Requirement Review Agent · {timestamp}{suffix}"


@tool(name="post_review_comment")
async def post_review_comment(
    issue_key: str,
    comment_markdown: str | None = None,
    findings: list[dict[str, Any]] | None = None,
    workflow_id: str | None = None,
    readiness: dict[str, Any] | None = None,
) -> dict[str, Any]:
    footer = _footer(workflow_id)

    if comment_markdown and comment_markdown.strip():
        adf = markdown_to_adf(comment_markdown, footer=footer)
    elif findings:
        readiness_model = Readiness.model_validate(readiness) if readiness else None
        adf = render_review_to_adf(
            parse_findings({"findings": findings}),
            issue_key,
            footer=footer,
            readiness=readiness_model,
        )
    else:
        return {
            "posted": False,
            "comment_id": None,
            "comment_url": None,
            "error": "Nothing to post: provide comment_markdown or findings.",
        }

    try:
        async with jira_client_from_env() as jira:
            await jira.preflight()
            result = await jira.post_comment(issue_key, adf)
            comment_id = result.get("id")
            comment_url = jira.browse_url(issue_key, comment_id)
    except Exception as e:
        logger.error("post_review_comment failed for %s: %s", issue_key, e, exc_info=True)
        return {"posted": False, "comment_id": None, "comment_url": None, "error": str(e)}

    return {"posted": True, "comment_id": comment_id, "comment_url": comment_url, "error": None}
